/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class SwarmMessageVect extends java.util.AbstractList<SwarmMessage> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwarmMessageVect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwarmMessageVect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_SwarmMessageVect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SwarmMessageVect(SwarmMessage[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SwarmMessage element : initialElements) {
      add(element);
    }
  }

  public SwarmMessageVect(Iterable<SwarmMessage> initialElements) {
    this();
    for (SwarmMessage element : initialElements) {
      add(element);
    }
  }

  public SwarmMessage get(int index) {
    return doGet(index);
  }

  public SwarmMessage set(int index, SwarmMessage e) {
    return doSet(index, e);
  }

  public boolean add(SwarmMessage e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SwarmMessage e) {
    modCount++;
    doAdd(index, e);
  }

  public SwarmMessage remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public SwarmMessageVect() {
    this(JamiServiceJNI.new_SwarmMessageVect__SWIG_0(), true);
  }

  public SwarmMessageVect(SwarmMessageVect other) {
    this(JamiServiceJNI.new_SwarmMessageVect__SWIG_1(SwarmMessageVect.getCPtr(other), other), true);
  }

  public long capacity() {
    return JamiServiceJNI.SwarmMessageVect_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    JamiServiceJNI.SwarmMessageVect_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return JamiServiceJNI.SwarmMessageVect_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JamiServiceJNI.SwarmMessageVect_clear(swigCPtr, this);
  }

  public SwarmMessageVect(int count, SwarmMessage value) {
    this(JamiServiceJNI.new_SwarmMessageVect__SWIG_2(count, SwarmMessage.getCPtr(value), value), true);
  }

  private int doSize() {
    return JamiServiceJNI.SwarmMessageVect_doSize(swigCPtr, this);
  }

  private void doAdd(SwarmMessage x) {
    JamiServiceJNI.SwarmMessageVect_doAdd__SWIG_0(swigCPtr, this, SwarmMessage.getCPtr(x), x);
  }

  private void doAdd(int index, SwarmMessage x) {
    JamiServiceJNI.SwarmMessageVect_doAdd__SWIG_1(swigCPtr, this, index, SwarmMessage.getCPtr(x), x);
  }

  private SwarmMessage doRemove(int index) {
    return new SwarmMessage(JamiServiceJNI.SwarmMessageVect_doRemove(swigCPtr, this, index), true);
  }

  private SwarmMessage doGet(int index) {
    return new SwarmMessage(JamiServiceJNI.SwarmMessageVect_doGet(swigCPtr, this, index), false);
  }

  private SwarmMessage doSet(int index, SwarmMessage val) {
    return new SwarmMessage(JamiServiceJNI.SwarmMessageVect_doSet(swigCPtr, this, index, SwarmMessage.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    JamiServiceJNI.SwarmMessageVect_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
