/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.jami.daemon;

public class SwarmMessage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SwarmMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwarmMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamiServiceJNI.delete_SwarmMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(String value) {
    JamiServiceJNI.SwarmMessage_id_set(swigCPtr, this, value);
  }

  public String getId() {
    return JamiServiceJNI.SwarmMessage_id_get(swigCPtr, this);
  }

  public void setType(String value) {
    JamiServiceJNI.SwarmMessage_type_set(swigCPtr, this, value);
  }

  public String getType() {
    return JamiServiceJNI.SwarmMessage_type_get(swigCPtr, this);
  }

  public void setLinearizedParent(String value) {
    JamiServiceJNI.SwarmMessage_linearizedParent_set(swigCPtr, this, value);
  }

  public String getLinearizedParent() {
    return JamiServiceJNI.SwarmMessage_linearizedParent_get(swigCPtr, this);
  }

  public void setBody(StringMap value) {
    JamiServiceJNI.SwarmMessage_body_set(swigCPtr, this, StringMap.getCPtr(value), value);
  }

  public StringMap getBody() {
    long cPtr = JamiServiceJNI.SwarmMessage_body_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringMap(cPtr, false);
  }

  public void setReactions(VectMap value) {
    JamiServiceJNI.SwarmMessage_reactions_set(swigCPtr, this, VectMap.getCPtr(value), value);
  }

  public VectMap getReactions() {
    long cPtr = JamiServiceJNI.SwarmMessage_reactions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectMap(cPtr, false);
  }

  public void setEditions(VectMap value) {
    JamiServiceJNI.SwarmMessage_editions_set(swigCPtr, this, VectMap.getCPtr(value), value);
  }

  public VectMap getEditions() {
    long cPtr = JamiServiceJNI.SwarmMessage_editions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectMap(cPtr, false);
  }

  public void setStatus(IntegerMap value) {
    JamiServiceJNI.SwarmMessage_status_set(swigCPtr, this, IntegerMap.getCPtr(value), value);
  }

  public IntegerMap getStatus() {
    long cPtr = JamiServiceJNI.SwarmMessage_status_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IntegerMap(cPtr, false);
  }

  public SwarmMessage() {
    this(JamiServiceJNI.new_SwarmMessage(), true);
  }

}
